import { useState, useMemo } from 'react'
import { Plus, Phone, X, AlertTriangle, UserCheck } from 'lucide-react'
import type { Cliente, Visita, Lead } from '../types'
import { GREMIOS_SUGERIDOS } from '../types'
import { todayISO, daysAgo } from '../utils'
import { DeleteButton, EmptyState } from './shared'

export function ClientesView({clientes,visitas,leads,onAddCliente,onDeleteCliente,onUpdateCliente,onAddLead,onSetLeadEstado,onDeleteLead,onConvertLead}:{clientes:Cliente[];visitas:Visita[];leads:Lead[];onAddCliente:(d:Partial<Cliente>)=>void;onDeleteCliente:(id:string)=>void;onUpdateCliente:(id:string,d:Partial<Cliente>)=>void;onAddLead:(d:Partial<Lead>)=>void;onSetLeadEstado:(id:string,e:string)=>void;onDeleteLead:(id:string)=>void;onConvertLead:(l:Lead)=>void}) {
  const [subView,setSubView] = useState('clientes')
  const [showForm,setShowForm] = useState(false)
  const [editing,setEditing] = useState<string|null>(null)
  const [form,setForm] = useState<Record<string,string>>({})
  const [showLeadForm,setShowLeadForm] = useState(false)
  const [leadForm,setLeadForm] = useState<Record<string,string>>({})
  const openEdit=(c:Cliente)=>{setForm(c as unknown as Record<string,string>);setEditing(c.id);setShowForm(true)}
  const submit=()=>{if(!form.nombre?.trim())return;if(editing)onUpdateCliente(editing,form);else onAddCliente(form);setShowForm(false)}
  const submitLead=()=>{if(!leadForm.nombre?.trim())return;onAddLead(leadForm);setLeadForm({});setShowLeadForm(false)}
  const stats=useMemo(()=>clientes.map(c=>{const vs=visitas.filter(v=>v.clienteId===c.id).sort((a,b)=>b.fecha.localeCompare(a.fecha));const last=vs[0]?.fecha;const fn=Number(c.frecuencia);let overdue=false;if(last&&fn>0){const exp=Math.round(7/fn);overdue=daysAgo(last)>exp*1.6}return{...c,lastVisit:last,overdue}}),[clientes,visitas])
  const leadsActivos=leads.filter(l=>l.estado==='nuevo'||l.estado==='contactado')
  const leadsArchivados=leads.filter(l=>l.estado==='convertido'||l.estado==='descartado')
  const nuevosCount=leads.filter(l=>l.estado==='nuevo').length
  const ELABEL:{[k:string]:string}={nuevo:'Nuevo',contactado:'Contactado',convertido:'Convertido',descartado:'Descartado'}
  return (
    <div className="aa-view">
      <div className="aa-subtabs">
        <button className={`aa-subtab${subView==='clientes'?' is-active':''}`} onClick={()=>setSubView('clientes')}>Clientes</button>
        <button className={`aa-subtab${subView==='leads'?' is-active':''}`} onClick={()=>setSubView('leads')}>Leads {nuevosCount>0&&<span className="aa-subtab__badge">{nuevosCount}</span>}</button>
      </div>
      {subView==='clientes'&&<><div className="aa-viewheader"><span>Clientes</span><button className="aa-addsmall" onClick={()=>{setForm({});setEditing(null);setShowForm(true)}}><Plus size={14}/> Cliente</button></div>{stats.length===0&&<EmptyState text="Sin clientes todavía."/>}<div className="aa-clientlist">{stats.map(c=>(<div key={c.id} className="aa-clientcard" onClick={()=>openEdit(c)}><div className="aa-clientcard__top"><span className="aa-clientcard__name">{c.nombre}</span>{c.overdue&&<span className="aa-flag"><AlertTriangle size={12}/> atrasado</span>}</div><div className="aa-clientcard__row">{c.telefono&&<span><Phone size={11}/> {c.telefono}</span>}{c.frecuencia&&<span className="aa-tag">{c.frecuencia}x/semana</span>}</div>{c.lastVisit?<div className="aa-clientcard__sub">Última visita: hace {daysAgo(c.lastVisit)} días</div>:<div className="aa-clientcard__sub">Sin visitas todavía</div>}</div>))}</div></>}
      {subView==='leads'&&<><div className="aa-viewheader"><span>Leads</span><button className="aa-addsmall" onClick={()=>setShowLeadForm(true)}><Plus size={14}/> Lead</button></div>{!leadsActivos.length&&!leadsArchivados.length&&<EmptyState text="Sin solicitudes todavía."/>}<div className="aa-clientlist">{leadsActivos.map(l=>(<div key={l.id} className="aa-clientcard"><div className="aa-clientcard__top"><span className="aa-clientcard__name">{l.nombre}</span><span className={`aa-tag${l.estado==='nuevo'?' aa-tag--estado-encurso':' aa-tag--gremio'}`}>{ELABEL[l.estado]}</span></div><div className="aa-clientcard__row">{l.telefono&&<span><Phone size={11}/> {l.telefono}</span>}{l.gremio&&<span className="aa-tag aa-tag--gremio">{l.gremio}</span>}</div>{l.mensaje&&<div className="aa-clientcard__sub">{l.mensaje}</div>}<div className="aa-leadactions">{l.estado==='nuevo'&&<button className="aa-addsmall" onClick={()=>onSetLeadEstado(l.id,'contactado')}>Marcar contactado</button>}<button className="aa-addsmall aa-addsmall--brass" onClick={()=>onConvertLead(l)}><UserCheck size={13}/> Convertir en cliente</button><button className="aa-addsmall" onClick={()=>onSetLeadEstado(l.id,'descartado')}>Descartar</button><DeleteButton onConfirm={()=>onDeleteLead(l.id)} label="lead"/></div></div>))}{leadsArchivados.length>0&&<><div className="aa-obrablock__title" style={{marginTop:10}}>Archivados</div>{leadsArchivados.map(l=>(<div key={l.id} className="aa-clientcard" style={{opacity:0.6}}><div className="aa-clientcard__top"><span className="aa-clientcard__name">{l.nombre}</span><span className="aa-tag aa-tag--gremio">{ELABEL[l.estado]}</span></div><DeleteButton onConfirm={()=>onDeleteLead(l.id)} label="lead"/></div>))}</>}</div></>}
      {showForm&&<div className="aa-overlay" onClick={()=>setShowForm(false)}><div className="aa-sheet" onClick={e=>e.stopPropagation()}><div className="aa-sheet__handle"/><div className="aa-sheet__title">{editing?'Editar cliente':'Nuevo cliente'}</div><label className="aa-label">Nombre</label><input className="aa-input" value={form.nombre||''} onChange={e=>setForm({...form,nombre:e.target.value})}/><label className="aa-label">Teléfono</label><input className="aa-input" value={form.telefono||''} onChange={e=>setForm({...form,telefono:e.target.value})}/><label className="aa-label">Dirección</label><input className="aa-input" value={form.direccion||''} onChange={e=>setForm({...form,direccion:e.target.value})}/><label className="aa-label">Frecuencia estimada (veces/semana)</label><input type="number" className="aa-input" value={form.frecuencia||''} onChange={e=>setForm({...form,frecuencia:e.target.value})}/><label className="aa-label">Notas</label><textarea className="aa-input aa-textarea" value={form.notas||''} onChange={e=>setForm({...form,notas:e.target.value})}/><button className="aa-submit aa-submit--brass" onClick={submit}>Guardar</button>{editing&&<button className="aa-submit aa-submit--danger" onClick={()=>{onDeleteCliente(editing);setShowForm(false)}}>Eliminar cliente</button>}<button className="aa-sheet__close" onClick={()=>setShowForm(false)}><X size={16}/> Cerrar</button></div></div>}
      {showLeadForm&&<div className="aa-overlay" onClick={()=>setShowLeadForm(false)}><div className="aa-sheet" onClick={e=>e.stopPropagation()}><div className="aa-sheet__handle"/><div className="aa-sheet__title">Nuevo lead</div><label className="aa-label">Nombre</label><input className="aa-input" value={leadForm.nombre||''} onChange={e=>setLeadForm({...leadForm,nombre:e.target.value})}/><label className="aa-label">Teléfono</label><input className="aa-input" value={leadForm.telefono||''} onChange={e=>setLeadForm({...leadForm,telefono:e.target.value})}/><label className="aa-label">Gremio que pide</label><input className="aa-input" list="aa-gr" value={leadForm.gremio||''} onChange={e=>setLeadForm({...leadForm,gremio:e.target.value})}/><datalist id="aa-gr">{GREMIOS_SUGERIDOS.map(g=><option key={g} value={g}/>)}</datalist><label className="aa-label">Mensaje</label><textarea className="aa-input aa-textarea" value={leadForm.mensaje||''} onChange={e=>setLeadForm({...leadForm,mensaje:e.target.value})}/><button className="aa-submit aa-submit--brass" onClick={submitLead}>Guardar lead</button><button className="aa-sheet__close" onClick={()=>setShowLeadForm(false)}><X size={16}/> Cerrar</button></div></div>}
    </div>
  )
}

export { todayISO }
